---
version: '3.5'
services:

  postgresql:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  solr:
    image: iqss/solr-k8s
    expose:
      - 8983

  dataverse:
    build:
      context: .
      dockerfile: ./docker/dataverse-k8s/payara/Dockerfile
    depends_on:
      - postgresql
      - solr
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - type: bind
        source: ./personas/docker-compose/secrets
        target: /secrets
        #read_only: true
